apiVersion: v1
kind: Secret
metadata:
  name: library-secret
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "pu20$$pru&n29jsudhg24t23.1u3en$$&unspdfh2$$p39u&fn3pu4n.14$$$$3314"
