apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserve-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserve-service
  template:
    metadata:
      labels:
        app: reserve-service
    spec:
      containers:
        - name: reserve-service
          image: library-reserve-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: library-configmap
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: library-secret
                  key: JWT_SECRET
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/library_reserves"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: library-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secret
                  key: DB_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
---
apiVersion: v1
kind: Service
metadata:
  name: reserve-service
spec:
  selector:
    app: reserve-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
